### PR TITLE
Added appveyor ci build fix #77

### LINKED ISSUE #77: Implement a C.I build
Maybe using AppVeyor, i.e. like this https://ci.appveyor.com/project/mattwarren/minibench-warren. This way if someone (probably me) breaks the build or some tests, we'll know about it sooner rather than later

See [this discussion](https://gitter.im/PerfDotNet/BenchmarkDotNet?at=569d478b5de13b3f15e3c9d0) for some background and extra info.

### PR DESCRIPTION
**Pull request by gigi81**
Added support for appveyor.
The build currently fails due to some tests failing, otherwise it should work properly.
This fix issue #77 
An example build can be found here:
https://ci.appveyor.com/project/gigi81/benchmarkdotnet

You will need to create an account on appveyor after the merge (and add a badge on the readme?).

### CODE REVIEW

**Comment by mattwarren** [comment]
@gigi81 thankyou so much for doing this, this is great! We really needed this and I just haven't had time to do it, so thanks!

> The build currently fails due to some tests failing, otherwise it should work properly.

Yep and this is exactly why we needed a CI build!! I'll open an issue to get those fixed.

A few questions:

1. Can this be made to run automatically on every check-in on the develop branch?
1. How easy is it to wire up so that we can get build the result, on a PR inside GitHub? I.e. like this https://github.com/HdrHistogram/HdrHistogram.NET/pull/28#issuecomment-223313311?

**Comment by gigi81** [comment]
Hi @mattwarren 
I'm glad you guys will enjoy it! I just love automation and I couldn't resist fixing it.

So first thing you need to do is create an account on appeveyor logging is as "PerfDotNet" github account and enable the build on the  "BenchmarkDotNet" project.

> Can this be made to run automatically on every check-in on the develop branch?

The build is already configured to run on every check-in for all branches (see top of the appveyor.yml)

> How easy is it to wire up so that we can get build the result, on a PR inside GitHub?

On the project settings in appeveyor you will find the webhook url. Copy that and paste in the github webhooks settings page.
Here more details:
http://help.appveyor.com/discussions/questions/203-auto-run-tests-on-pull-requests

As a side note, I couldn't wire the .net core tests in the test tab in appveyor. They are run but if they fail you can only see it in the console. So only .net "classic" for the moment is in that tab.
I will have a look at this when I have some more spare time.

**Comment by mattwarren** [comment]
> As a side note, I couldn't wire the .net core tests in the test tab in appveyor. They are run but if they fail you can only see it in the console. So only .net "classic" for the moment is in that tab.
I will have a look at this when I have some more spare time.

On a related note, is there any way to make the [test output](https://ci.appveyor.com/project/gigi81/benchmarkdotnet/build/tests), display more info from the log? For instance when `BenchmarkDotNet.IntegrationTests.MemoryDiagnoserTests.Test` is run, the Console log contains the following (lines 9648 - 9934), it would be nice to be able to see these on the "TESTS" page, does AppVeyor allow that?

```
// ***** BenchmarkRunner: Start   *****
// Found benchmarks:
//   ListEnumeratorsBenchmarks_ListStructEnumerator_WarmupCount5_TargetCount5_LaunchCount1
//   ListEnumeratorsBenchmarks_ListObjectEnumerator_WarmupCount5_TargetCount5_LaunchCount1
// Validating benchmarks:
// **************************
// Benchmark: ListEnumeratorsBenchmarks_ListStructEnumerator_WarmupCount5_TargetCount5_LaunchCount1
// *** Generate *** 
// Result = Success 
// DirectoryPath = C:\projects\benchmarkdotnet\BenchmarkDotNet.IntegrationTests\bin\Release\net451\win7-x64\BenchmarkDotNet.Artifacts\bin\BDN.Auto
// *** Build ***
// Result = Success 
// *** Execute *** 
// Launch: 1 / 1 
// BenchmarkDotNet-Dev=v0.9.7.0+ 
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Xeon(R) CPU 2.30GHz, ProcessorCount=1
// Frequency=10000000 ticks, Resolution=100.0000 ns, Timer=UNKNOWN
// CLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
// JitModules=clrjit-v4.6.1055.0
Pilot 1: 4 op, 484500 ns, 121.1250 us/op
Pilot 2: 8 op, 7800 ns, 975.0000 ns/op
Pilot 3: 16 op, 7700 ns, 481.2500 ns/op
Pilot 4: 32 op, 13200 ns, 412.5000 ns/op
Pilot 5: 64 op, 23600 ns, 368.7500 ns/op
Pilot 6: 128 op, 45300 ns, 353.9063 ns/op
Pilot 7: 256 op, 90600 ns, 353.9063 ns/op
Pilot 8: 512 op, 189800 ns, 370.7031 ns/op
Pilot 9: 1024 op, 412800 ns, 403.1250 ns/op
Pilot 10: 2048 op, 698900 ns, 341.2598 ns/op
Pilot 11: 4096 op, 1395000 ns, 340.5762 ns/op
Pilot 12: 8192 op, 3081600 ns, 376.1719 ns/op
Pilot 13: 16384 op, 5746700 ns, 350.7507 ns/op
Pilot 14: 32768 op, 11731100 ns, 358.0048 ns/op
Pilot 15: 65536 op, 23871900 ns, 364.2563 ns/op
Pilot 16: 131072 op, 46495600 ns, 354.7333 ns/op
Pilot 17: 262144 op, 93207600 ns, 355.5588 ns/op
Pilot 18: 524288 op, 182549300 ns, 348.1852 ns/op
Pilot 19: 1048576 op, 374746700 ns, 357.3863 ns/op
IdleWarmup 1: 1048576 op, 2852900 ns, 2.7207 ns/op
IdleWarmup 2: 1048576 op, 2737300 ns, 2.6105 ns/op
IdleWarmup 3: 1048576 op, 2768200 ns, 2.6400 ns/op
IdleWarmup 4: 1048576 op, 2809300 ns, 2.6792 ns/op
IdleWarmup 5: 1048576 op, 2805900 ns, 2.6759 ns/op
IdleWarmup 6: 1048576 op, 2747900 ns, 2.6206 ns/op
IdleWarmup 7: 1048576 op, 2751500 ns, 2.6240 ns/op
IdleTarget 1: 1048576 op, 2746100 ns, 2.6189 ns/op
IdleTarget 2: 1048576 op, 2756700 ns, 2.6290 ns/op
IdleTarget 3: 1048576 op, 2759100 ns, 2.6313 ns/op
IdleTarget 4: 1048576 op, 2993100 ns, 2.8544 ns/op
IdleTarget 5: 1048576 op, 2839600 ns, 2.7081 ns/op
IdleTarget 6: 1048576 op, 2753300 ns, 2.6258 ns/op
IdleTarget 7: 1048576 op, 3097000 ns, 2.9535 ns/op
IdleTarget 8: 1048576 op, 2815300 ns, 2.6849 ns/op
IdleTarget 9: 1048576 op, 2853900 ns, 2.7217 ns/op
IdleTarget 10: 1048576 op, 2918900 ns, 2.7837 ns/op
MainWarmup 1: 1048576 op, 400843800 ns, 382.2744 ns/op
MainWarmup 2: 1048576 op, 432105100 ns, 412.0875 ns/op
MainWarmup 3: 1048576 op, 383633500 ns, 365.8614 ns/op
MainWarmup 4: 1048576 op, 407287100 ns, 388.4192 ns/op
MainWarmup 5: 1048576 op, 391920800 ns, 373.7648 ns/op
MainTarget 1: 1048576 op, 378612600 ns, 361.0731 ns/op
MainTarget 2: 1048576 op, 416428100 ns, 397.1368 ns/op
MainTarget 3: 1048576 op, 371784600 ns, 354.5614 ns/op
MainTarget 4: 1048576 op, 366945400 ns, 349.9464 ns/op
MainTarget 5: 1048576 op, 391455600 ns, 373.3212 ns/op
Result 1: 1048576 op, 375785150 ns, 358.3766 ns/op
Result 2: 1048576 op, 413600650 ns, 394.4403 ns/op
Result 3: 1048576 op, 368957150 ns, 351.8650 ns/op
Result 4: 1048576 op, 364117950 ns, 347.2499 ns/op
Result 5: 1048576 op, 388628150 ns, 370.6247 ns/op
// Run, Diagnostic
// BenchmarkDotNet-Dev=v0.9.7.0+ 
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Xeon(R) CPU 2.30GHz, ProcessorCount=1
// Frequency=10000000 ticks, Resolution=100.0000 ns, Timer=UNKNOWN
// CLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
// JitModules=clrjit-v4.6.1055.0
Pilot 1: 4 op, 471900 ns, 117.9750 us/op
Pilot 2: 8 op, 7800 ns, 975.0000 ns/op
Pilot 3: 16 op, 7500 ns, 468.7500 ns/op
Pilot 4: 32 op, 13000 ns, 406.2500 ns/op
Pilot 5: 64 op, 23800 ns, 371.8750 ns/op
Pilot 6: 128 op, 45200 ns, 353.1250 ns/op
Pilot 7: 256 op, 96700 ns, 377.7344 ns/op
Pilot 8: 512 op, 174600 ns, 341.0156 ns/op
Pilot 9: 1024 op, 352800 ns, 344.5313 ns/op
Pilot 10: 2048 op, 781900 ns, 381.7871 ns/op
Pilot 11: 4096 op, 1557900 ns, 380.3467 ns/op
Pilot 12: 8192 op, 2908500 ns, 355.0415 ns/op
Pilot 13: 16384 op, 5865900 ns, 358.0261 ns/op
Pilot 14: 32768 op, 12467800 ns, 380.4871 ns/op
Pilot 15: 65536 op, 25908300 ns, 395.3293 ns/op
Pilot 16: 131072 op, 52720800 ns, 402.2278 ns/op
Pilot 17: 262144 op, 92728500 ns, 353.7312 ns/op
Pilot 18: 524288 op, 183359800 ns, 349.7311 ns/op
Pilot 19: 1048576 op, 372786700 ns, 355.5171 ns/op
IdleWarmup 1: 1048576 op, 2742900 ns, 2.6158 ns/op
IdleWarmup 2: 1048576 op, 2802300 ns, 2.6725 ns/op
IdleWarmup 3: 1048576 op, 2755000 ns, 2.6274 ns/op
IdleWarmup 4: 1048576 op, 2748200 ns, 2.6209 ns/op
IdleWarmup 5: 1048576 op, 2867600 ns, 2.7348 ns/op
IdleWarmup 6: 1048576 op, 2989300 ns, 2.8508 ns/op
IdleTarget 1: 1048576 op, 2805000 ns, 2.6751 ns/op
IdleTarget 2: 1048576 op, 2924000 ns, 2.7885 ns/op
IdleTarget 3: 1048576 op, 2922900 ns, 2.7875 ns/op
IdleTarget 4: 1048576 op, 2758400 ns, 2.6306 ns/op
IdleTarget 5: 1048576 op, 2794700 ns, 2.6652 ns/op
IdleTarget 6: 1048576 op, 2982600 ns, 2.8444 ns/op
IdleTarget 7: 1048576 op, 2783900 ns, 2.6549 ns/op
IdleTarget 8: 1048576 op, 2854200 ns, 2.7220 ns/op
IdleTarget 9: 1048576 op, 2931100 ns, 2.7953 ns/op
IdleTarget 10: 1048576 op, 2937000 ns, 2.8009 ns/op
MainWarmup 1: 1048576 op, 379565400 ns, 361.9818 ns/op
MainWarmup 2: 1048576 op, 362911200 ns, 346.0991 ns/op
MainWarmup 3: 1048576 op, 365102300 ns, 348.1887 ns/op
MainWarmup 4: 1048576 op, 373428600 ns, 356.1293 ns/op
MainWarmup 5: 1048576 op, 370750800 ns, 353.5755 ns/op
MainTarget 1: 1048576 op, 519164800 ns, 495.1141 ns/op
MainTarget 2: 1048576 op, 376483000 ns, 359.0422 ns/op
MainTarget 3: 1048576 op, 368275800 ns, 351.2152 ns/op
MainTarget 4: 1048576 op, 369397400 ns, 352.2848 ns/op
MainTarget 5: 1048576 op, 370797800 ns, 353.6203 ns/op
Result 1: 1048576 op, 516276250 ns, 492.3594 ns/op
Result 2: 1048576 op, 373594450 ns, 356.2874 ns/op
Result 3: 1048576 op, 365387250 ns, 348.4604 ns/op
Result 4: 1048576 op, 366508850 ns, 349.5301 ns/op
Result 5: 1048576 op, 367909250 ns, 350.8656 ns/op
Mean = 364.5113 ns, StdError = 8.4517 ns (2.32%); N = 5, StdDev = 18.8987 ns 
Min = 347.2499 ns, Q1 = 349.5574 ns, Median = 358.3766 ns, Q3 = 382.5325 ns, Max = 394.4403 ns
IQR = 32.9751 ns, LowerFence = 300.0949 ns, UpperFence = 431.9951 ns
ConfidenceInterval = [347.9459 ns; 381.0767 ns] (CI 95%)
// **************************
// Benchmark: ListEnumeratorsBenchmarks_ListObjectEnumerator_WarmupCount5_TargetCount5_LaunchCount1
// *** Generate *** 
// Result = Success 
// DirectoryPath = C:\projects\benchmarkdotnet\BenchmarkDotNet.IntegrationTests\bin\Release\net451\win7-x64\BenchmarkDotNet.Artifacts\bin\BDN.Auto
// *** Build ***
// Result = Success 
// *** Execute *** 
// Launch: 1 / 1 
// BenchmarkDotNet-Dev=v0.9.7.0+ 
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Xeon(R) CPU 2.30GHz, ProcessorCount=1
// Frequency=10000000 ticks, Resolution=100.0000 ns, Timer=UNKNOWN
// CLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
// JitModules=clrjit-v4.6.1055.0
Pilot 1: 4 op, 675100 ns, 168.7750 us/op
Pilot 2: 8 op, 19800 ns, 2.4750 us/op
Pilot 3: 16 op, 28800 ns, 1.8000 us/op
Pilot 4: 32 op, 53900 ns, 1.6844 us/op
Pilot 5: 64 op, 82100 ns, 1.2828 us/op
Pilot 6: 128 op, 176000 ns, 1.3750 us/op
Pilot 7: 256 op, 325800 ns, 1.2727 us/op
Pilot 8: 512 op, 757400 ns, 1.4793 us/op
Pilot 9: 1024 op, 1483700 ns, 1.4489 us/op
Pilot 10: 2048 op, 3086900 ns, 1.5073 us/op
Pilot 11: 4096 op, 6117600 ns, 1.4936 us/op
Pilot 12: 8192 op, 12066500 ns, 1.4730 us/op
Pilot 13: 16384 op, 24473100 ns, 1.4937 us/op
Pilot 14: 32768 op, 49825700 ns, 1.5206 us/op
Pilot 15: 65536 op, 88586000 ns, 1.3517 us/op
Pilot 16: 131072 op, 124381700 ns, 948.9571 ns/op
Pilot 17: 262144 op, 277535300 ns, 1.0587 us/op
IdleWarmup 1: 262144 op, 704800 ns, 2.6886 ns/op
IdleWarmup 2: 262144 op, 783200 ns, 2.9877 ns/op
IdleWarmup 3: 262144 op, 690100 ns, 2.6325 ns/op
IdleWarmup 4: 262144 op, 690800 ns, 2.6352 ns/op
IdleWarmup 5: 262144 op, 729800 ns, 2.7840 ns/op
IdleTarget 1: 262144 op, 977700 ns, 3.7296 ns/op
IdleTarget 2: 262144 op, 699400 ns, 2.6680 ns/op
IdleTarget 3: 262144 op, 700600 ns, 2.6726 ns/op
IdleTarget 4: 262144 op, 691700 ns, 2.6386 ns/op
IdleTarget 5: 262144 op, 696800 ns, 2.6581 ns/op
IdleTarget 6: 262144 op, 721400 ns, 2.7519 ns/op
IdleTarget 7: 262144 op, 688800 ns, 2.6276 ns/op
IdleTarget 8: 262144 op, 700200 ns, 2.6711 ns/op
IdleTarget 9: 262144 op, 687200 ns, 2.6215 ns/op
IdleTarget 10: 262144 op, 697700 ns, 2.6615 ns/op
MainWarmup 1: 262144 op, 291842600 ns, 1.1133 us/op
MainWarmup 2: 262144 op, 374433300 ns, 1.4283 us/op
MainWarmup 3: 262144 op, 345216200 ns, 1.3169 us/op
MainWarmup 4: 262144 op, 363626800 ns, 1.3871 us/op
MainWarmup 5: 262144 op, 340240900 ns, 1.2979 us/op
MainTarget 1: 262144 op, 352194500 ns, 1.3435 us/op
MainTarget 2: 262144 op, 357720700 ns, 1.3646 us/op
MainTarget 3: 262144 op, 304246500 ns, 1.1606 us/op
MainTarget 4: 262144 op, 287391800 ns, 1.0963 us/op
MainTarget 5: 262144 op, 297833200 ns, 1.1361 us/op
Result 1: 262144 op, 351495950 ns, 1.3409 us/op
Result 2: 262144 op, 357022150 ns, 1.3619 us/op
Result 3: 262144 op, 303547950 ns, 1.1579 us/op
Result 4: 262144 op, 286693250 ns, 1.0936 us/op
Result 5: 262144 op, 297134650 ns, 1.1335 us/op
// Run, Diagnostic
// BenchmarkDotNet-Dev=v0.9.7.0+ 
// OS=Microsoft Windows NT 6.2.9200.0
// Processor=Intel(R) Xeon(R) CPU 2.30GHz, ProcessorCount=1
// Frequency=10000000 ticks, Resolution=100.0000 ns, Timer=UNKNOWN
// CLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
// JitModules=clrjit-v4.6.1055.0
Pilot 1: 4 op, 673900 ns, 168.4750 us/op
Pilot 2: 8 op, 12700 ns, 1.5875 us/op
Pilot 3: 16 op, 23400 ns, 1.4625 us/op
Pilot 4: 32 op, 31400 ns, 981.2500 ns/op
Pilot 5: 64 op, 71200 ns, 1.1125 us/op
Pilot 6: 128 op, 116000 ns, 906.2500 ns/op
Pilot 7: 256 op, 231400 ns, 903.9063 ns/op
Pilot 8: 512 op, 566800 ns, 1.1070 us/op
Pilot 9: 1024 op, 929800 ns, 908.0078 ns/op
Pilot 10: 2048 op, 2161400 ns, 1.0554 us/op
Pilot 11: 4096 op, 5917800 ns, 1.4448 us/op
Pilot 12: 8192 op, 7668000 ns, 936.0352 ns/op
Pilot 13: 16384 op, 15670600 ns, 956.4575 ns/op
Pilot 14: 32768 op, 32631600 ns, 995.8374 ns/op
Pilot 15: 65536 op, 78722100 ns, 1.2012 us/op
Pilot 16: 131072 op, 138892600 ns, 1.0597 us/op
Pilot 17: 262144 op, 295917500 ns, 1.1288 us/op
IdleWarmup 1: 262144 op, 719400 ns, 2.7443 ns/op
IdleWarmup 2: 262144 op, 790300 ns, 3.0148 ns/op
IdleWarmup 3: 262144 op, 735100 ns, 2.8042 ns/op
IdleWarmup 4: 262144 op, 968800 ns, 3.6957 ns/op
IdleWarmup 5: 262144 op, 710800 ns, 2.7115 ns/op
IdleWarmup 6: 262144 op, 735000 ns, 2.8038 ns/op
IdleTarget 1: 262144 op, 720900 ns, 2.7500 ns/op
IdleTarget 2: 262144 op, 739500 ns, 2.8210 ns/op
IdleTarget 3: 262144 op, 740000 ns, 2.8229 ns/op
IdleTarget 4: 262144 op, 723900 ns, 2.7615 ns/op
IdleTarget 5: 262144 op, 717500 ns, 2.7370 ns/op
IdleTarget 6: 262144 op, 695100 ns, 2.6516 ns/op
IdleTarget 7: 262144 op, 874500 ns, 3.3360 ns/op
IdleTarget 8: 262144 op, 705900 ns, 2.6928 ns/op
IdleTarget 9: 262144 op, 745300 ns, 2.8431 ns/op
IdleTarget 10: 262144 op, 820500 ns, 3.1300 ns/op
MainWarmup 1: 262144 op, 271693500 ns, 1.0364 us/op
MainWarmup 2: 262144 op, 262745800 ns, 1.0023 us/op
MainWarmup 3: 262144 op, 266999500 ns, 1.0185 us/op
MainWarmup 4: 262144 op, 266398100 ns, 1.0162 us/op
MainWarmup 5: 262144 op, 266655300 ns, 1.0172 us/op
MainTarget 1: 262144 op, 284323700 ns, 1.0846 us/op
MainTarget 2: 262144 op, 308001400 ns, 1.1749 us/op
MainTarget 3: 262144 op, 300298800 ns, 1.1455 us/op
MainTarget 4: 262144 op, 285060600 ns, 1.0874 us/op
MainTarget 5: 262144 op, 262080600 ns, 999.7581 ns/op
Result 1: 262144 op, 283592000 ns, 1.0818 us/op
Result 2: 262144 op, 307269700 ns, 1.1721 us/op
Result 3: 262144 op, 299567100 ns, 1.1428 us/op
Result 4: 262144 op, 284328900 ns, 1.0846 us/op
Result 5: 262144 op, 261348900 ns, 996.9669 ns/op
Mean = 1.2176 us, StdError = 0.0557 us (4.57%); N = 5, StdDev = 0.1245 us 
Min = 1.0936 us, Q1 = 1.1136 us, Median = 1.1579 us, Q3 = 1.3514 us, Max = 1.3619 us
IQR = 0.2378 us, LowerFence = 0.7568 us, UpperFence = 1.7081 us
ConfidenceInterval = [1.1084 us; 1.3267 us] (CI 95%)
// ***** BenchmarkRunner: Finish  *****
// * Export *
// * Detailed results *
ListEnumeratorsBenchmarks_ListStructEnumerator_WarmupCount5_TargetCount5_LaunchCount1
Mean = 364.5113 ns, StdError = 8.4517 ns (2.32%); N = 5, StdDev = 18.8987 ns
Min = 347.2499 ns, Q1 = 349.5574 ns, Median = 358.3766 ns, Q3 = 382.5325 ns, Max = 394.4403 ns
IQR = 32.9751 ns, LowerFence = 300.0949 ns, UpperFence = 431.9951 ns
ConfidenceInterval = [347.9459 ns; 381.0767 ns] (CI 95%)
ListEnumeratorsBenchmarks_ListObjectEnumerator_WarmupCount5_TargetCount5_LaunchCount1
Mean = 1.2176 us, StdError = 0.0557 us (4.57%); N = 5, StdDev = 0.1245 us
Min = 1.0936 us, Q1 = 1.1136 us, Median = 1.1579 us, Q3 = 1.3514 us, Max = 1.3619 us
IQR = 0.2378 us, LowerFence = 0.7568 us, UpperFence = 1.7081 us
ConfidenceInterval = [1.1084 us; 1.3267 us] (CI 95%)
Total time: 00:00:28 (28.15 sec)
// * Summary *
BenchmarkDotNet-Dev=v0.9.7.0+
OS=Microsoft Windows NT 6.2.9200.0
Processor=Intel(R) Xeon(R) CPU 2.30GHz, ProcessorCount=1
Frequency=10000000 ticks, Resolution=100.0000 ns, Timer=UNKNOWN
HostCLR=MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1055.0
Type=ListEnumeratorsBenchmarks  Mode=Throughput  LaunchCount=1  
WarmupCount=5  TargetCount=5  
               Method |        Median |      StdDev | Gen 0 | Gen 1 | Gen 2 | Bytes Allocated/Op |
--------------------- |-------------- |------------ |------ |------ |------ |------------------- |
 ListStructEnumerator |   358.3766 ns |  18.8987 ns |     - |     - |     - |               0.04 |
 ListObjectEnumerator | 1,157.9435 ns | 124.5207 ns |     - |     - |     - |              14.76 |
// * Diagnostic Output - MemoryDiagnoser *
// ***** BenchmarkRunner: End *****
    BenchmarkDotNet.IntegrationTests.MemoryDiagnoserTests.Test [FAIL] 
      System.FormatException : Input string was not in a correct format. 
      Stack Trace: 
           at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt) 
        BenchmarkDotNet.IntegrationTests\MemoryDiagnoserTests.cs(80,0): at BenchmarkDotNet.IntegrationTests.MemoryDiagnoserTests.Test() 
```

**Comment by adamsitnik** [comment]
# I just love it!!!!!!

The only thing I would like to ask you is to create PR that will merge to our develop branch. We use master only for the code that was released for latest nuget package.

**Comment by gigi81** [comment]
Hi @mattwarren ,
I didn't  look at the code but I think that the output for the test is written directly to the console.
That is the "old" way of doing it and the latest versions of xunit you need to write the output to a specific interface ITestOutputHelper.

https://xunit.github.io/docs/capturing-output.html

If you are wondering, the reason for this change is due to the fact that modern unittest frameworks can run test simultaneously in separate threads. If they write to the console, xunit has no way to tell from which test the message comes from. So I guess you should open an issue to use ITestOutputHelper instead of console in the tests.

Let me know guys when you have the build setup in appveyor.

**Comment by mattwarren** [comment]
@AndreyAkinshin I think that as you are the owner, you'll need to setup the appveyor build in the BenchmarkDotNet GitHub account. When you get a chance can you follow through [these steps](https://github.com/PerfDotNet/BenchmarkDotNet/pull/199#issuecomment-223918228)?

**Comment by gigi81** [comment]
Hi @AndreyAkinshin did you had a chance to had a look at the comment above https://github.com/PerfDotNet/BenchmarkDotNet/pull/199#issuecomment-223918228

**Comment by gigi81** [comment]
Hi @AndreyAkinshin. I see you wired it all up. That is great! I had 2 other pull requests. One you already merged. That was quick! The second one #206 is to add all the tests in the "tests" tab in appveyor as explained above.

**Comment by AndreyAkinshin** [comment]
@gigi81, can you take a look at this build results: https://ci.appveyor.com/project/PerfDotNet/benchmarkdotnet/build/0.9.7.12 ?

All tests are passed, there are no any warnings. Why the build is failed?

**Comment by gigi81** [comment]
Hi,
"dotnet test" is failing with this error:
error: ' ', hexadecimal value 0x1B, is an invalid character.

When the tests complete "dotnet test" generates an xml file with the
results.
The file is then uploaded to appveyor by a ps script so that you can see
the results in the tests tab.

Seems like the XML contains an invalid character, probably from the std
output captured.
This might be a dotnet-test bug.
Anyway, for the moment, I think we should fix this in the OutputLogger so
that invalid characters are not written to the std output
Something like this:
http://stackoverflow.com/a/14322933/789165

I will have some tests and see if this fix the problem and eventually a PR.

**Comment by gigi81** [comment]
It's definitely a xunit bug: https://github.com/xunit/xunit/issues/876
I think we can temporarily go for the workaround suggested before while they fix it.

**Comment by AndreyAkinshin** [comment]
LGTM. Waiting for the PR.

**Comment by AndreyAkinshin** [comment]
I close this issues as an obsolete.

**Comment by AndreyAkinshin** [comment]
@gigi81, use https://github.com/PerfDotNet/BenchmarkDotNet/issues/209 for the future discussions.

**Pull request closed without merging**
