### PR TITLE
Percentiles added into Statistics, StatisticColumn, BaselineDiffColumn

### PR DESCRIPTION
**Pull request by ig-sinicyn**
Redone as #164. This one will be closed

As I wrote [here](https://github.com/PerfDotNet/BenchmarkDotNet/issues/126#issuecomment-200302063) I begin to do small PR to make it easier to use BenchmarkDotNet as an competition tests runner.

This PR adds Nth percentile and Nth percenile scaled columns. These should be used to rank and to compare competitors if the timings are varying from run to run.

More info on these: 
http://www.goland.org/average_percentile_services/
http://apmblog.dynatrace.com/2012/11/14/why-averages-suck-and-percentiles-are-great/

P.S. I'm not sure that proposed API design is good enough so it's definitely subject to discuss:)

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@ig-sinicyn, thanks for the PR.

Can you use an integer value for percentile instead of `PercentileLevel`?

**Comment by ig-sinicyn** [comment]
@AndreyAkinshin, yes, of course :)

Just to clarify. There're two overloads of the PercentileValues.Percentile method, first takes enum and second - double value in range 0..1.

The first should be removed and the second should be changed to accept int in range 0..100, right?

**Comment by AndreyAkinshin** [comment]
> The first should be removed and the second should be changed to accept int in range 0..100, right?

Yep, LGTM.

**Comment by ig-sinicyn** [comment]
Ok, will do.

**Comment by mattwarren** [comment]
Firstly thanks for doing this, having percentiles is great!

Secondly, I'm a bit late to this PR, but I think it would be nice if there was an [integration test](https://github.com/PerfDotNet/BenchmarkDotNet/tree/master/BenchmarkDotNet.IntegrationTests) that covered this new feature.

You could create a brand new test, or extend the relevant existing ones, i.e. BaselineDiffColumnTest.cs, StatResultExtenderTests.cs, etc)

**Comment by ig-sinicyn** [comment]
@mattwarren Not a problem, will do :)

It looks that the PR is slightly outdated. Should I close it and create a new one from a current develop branch?

**Comment by mattwarren** [comment]
> It looks that the PR is slightly outdated. Should I close it and create a new one from a current develop branch?

Sorry, I'm not a GitHub expert. If that's easiest go ahead and create a new one

**Comment by ig-sinicyn** [comment]
Well, me too :)

Ok, I'll push the commits into the current pull request and if there will be some troubles with the merging I'll redo the PR.

**Comment by goldshtn** [comment]
What you're looking for is squash :-)

**Comment by ig-sinicyn** [comment]
Well, it turns out I'll have to redo the PR. The BaselineDiffColumnTest in the month-old version is failing.

I'll close this after submitting a new one.

**Comment by ig-sinicyn** [comment]
Redone as #164

**Pull request closed without merging**
