### PR TITLE
Added documentation source and output based on readme.md

### PR DESCRIPTION
**Pull request by FransBouma**
The documentation is created from the readme.md file and uses docnet
v0.13 or higher to generate its output. Documentation\UserGuideSource is
the folder which contains the markdown. Run generatehtml.cmd which will
generate html files from the md files into documentation\userguidehtml.
I committed the html output as well so there's an initial batch.
Configure where the files are generated in
documentation\userguidesource\docnet.json as well as other things
related to the html generation process.

For #219

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@FransBouma, we shouldn't keep the generated documentation in the master branch. Here we need only documentation sources and building scripts/infrastructure. Also I suggest to do a few folder renaming: `documentation` -> `docs`, `UserGuideSource` -> `guide`.

**Comment by FransBouma** [comment]
> we shouldn't keep the generated documentation in the master branch

Ok, will remove that. 

> Here we need only documentation sources and building scripts/infrastructure. Also I suggest to do a few folder renaming: documentation -> docs, UserGuideSource -> guide.

Ok. The 'documentation' folder is linked to in the current develop.md file btw, so I'll adjust that too.

**Comment by AndreyAkinshin** [comment]
Awesome! I will review it tonight.

**Comment by FransBouma** [comment]
:) The 'documentation' folder wasn't referenced by the original develop.md so that's fine. The images folder in the documentation folder was unused. 

I just noticed I left an unused include in the docnet.json file: the Images folder isn't there anymore and therefore the 
```
	"SourceFoldersToCopy" : ["Images"],
```
line isn't needed anymore. It won't break or anything, but it's not needed anymore. Should I remove it or leave it? Removing it will trigger another appveyor build for no real reason. 

The docnet.json file dictates now to build the html to docs\guidehtml. This folder is excluded in gitignore, but you can change it to any other folder you want.

**Comment by AndreyAkinshin** [comment]
> Should I remove it or leave it? Removing it will trigger another appveyor build for no real reason.

Don't hesitate to do any improvements, nothing wrong with additional appveyor builds.

**Comment by FransBouma** [comment]
Agreed. :) Done.

**Comment by FransBouma** [comment]
Any problems with the PR?

**Comment by AndreyAkinshin** [comment]
@FransBouma, sorry for the late merge, I was too busy on this week. Thanks again, it looks awesome! Waiting for a PR with API reference.

**Comment by FransBouma** [comment]
@AndreyAkinshin I haven't created a setup for the API ref docs as there are no xml doc comments in the source, so creating that would be a bit odd. If you really really want to, I could create one, but the end results are barely useable. (you can see what properties there are etc. but nothing tells you what they mean).

**Comment by AndreyAkinshin** [comment]
I really really want to have it. =) In fact, I want to have a way to build the API reference. I will not publish it online for now, but I just want to have a possibility to do it as soon as xml-docs will be ready.

**Pull request merged**
