### PR TITLE
Add support for exporting to asciidoc

### PR DESCRIPTION
**Pull request by russcam**
Add support for exporting to [asciidoc](http://asciidoc.org/userguide.html)

### CODE REVIEW

**Comment by mattwarren** [comment]
Thanks for submitting this, look good.

Just for my own curiosity, could you paste a sample asciidoc output into this PR? I'm intrigued to see what the BenchmarkDotNet output looks like.

**Comment by russcam** [comment]
Sure, Here's one from a benchmark I ran earlier
```
....
BenchmarkDotNet=v0.9.5.0
OS=Microsoft Windows NT 6.1.7601 Service Pack 1
Processor=Intel(R) Core(TM) i7-2920XM CPU @ 2.50GHz, ProcessorCount=8
Frequency=2433574 ticks, Resolution=410.9183 ns, Timer=TSC
HostCLR=DNX MS.NET 4.0.30319.42000, Arch=64-bit RELEASE [RyuJIT]
JitModules=clrjit-v4.6.1076.0
.NET Command Line Tools (1.0.0-beta-001598)

Type=FieldResolverBenchmarkTests  Mode=Throughput  
....
[options="header"]
|===
|                           Method|          Median|       StdDev
|    NonCachedFieldUsingExpression|  12,016.3370 ns|  483.9973 ns
|       CachedFieldUsingExpression|   6,830.6822 ns|  136.2565 ns
|  NonCachedFieldUsingPropertyInfo|   1,960.8515 ns|   24.8604 ns
|     CachedFieldUsingPropertyInfo|     187.9910 ns|    2.0045 ns
|        NonCachedFieldUsingString|     101.0201 ns|    2.1527 ns
|           CachedFieldUsingString|     111.3235 ns|    3.1101 ns
|===
```
It's not too dissimilar from Markdown (but with more features to allow writing technical documentation) and Github has some basic support for asciidoc. Take a look at the [automapping documentation from NEST](https://github.com/elastic/elasticsearch-net/blob/master/docs/client-concepts/high-level/mapping/auto-map.asciidoc) for example. There's also the [Asciidoctor Live Preview chrome extension](https://chrome.google.com/webstore/detail/asciidoctorjs-live-previe/iaalpfgpbocpdfblpnhhgllgbdbchmia?hl=en) to view them in the browser

**Comment by russcam** [comment]
I was thinking that the Environment info could be a [labeled list](http://asciidoc.org/userguide.html#_labeled_lists) in a delimited block too, might be a bit more readable.

**Comment by mattwarren** [comment]
> I was thinking that the Environment info could be a labeled list in a delimited block too, might be a bit more readable.

That's a nice idea, are you happy to add that to this PR and then I'll pull it in?

**Comment by russcam** [comment]
Sure, no worries. I'll do it first thing in the morning, getting late here in Oz :+1:

**Comment by russcam** [comment]
Not sure what's happened to the spaces in that commit; will fix now

**Comment by AndreyAkinshin** [comment]
@russcam, `AsciiDocExporter` looks good to me, thanks. However, I have the following concerns:
1. Did you try to run any benchmark with your last changes? It's impossible to build any benchmarks because we use `EnvironmentInfo.GetCurrent().ToFormattedString()` in the generated `Program.cs` file. I suggest to revert `EnvironmentInfo` changes. We can refactor the `ToFormattedString` method later, but we should do it carefully in a separated commit.
P.S. Always run tests before commits, it is a good practice (`runClassicTests.cmd`, `runDnxAndCoreTests.cmd`).
2. We accept PRs only in the `develop` branch, not `master`.

**Comment by russcam** [comment]
Serves me right for rushing it :smile: I didn't run with the last set of changes, was having some issues being able to build the `master` branch.

I'll close this PR, open one against the `develop` branch without the `ToFormattedString()` changes

**Comment by AndreyAkinshin** [comment]
@russcam, sounds good to me.

**Pull request closed without merging**
