### PR TITLE
Add support of Cleanup attribute #215

### PR DESCRIPTION
**Pull request by DenisIstomin**

### CODE REVIEW

**Comment by AndreyAkinshin** [comment]
@DenisIstomin, thanks for the PR. Code looks good, but I don't like your example: `List_LinkedListAllocation`. Benchmarks in this class don't have a steady state, so, we can't benchmark it with default settings (cleanup doesn't help in this case). Can you write another example?

**Comment by DenisIstomin** [comment]
Wrote another example. I think that there are some redundant [operations](https://github.com/DenisIstomin/BenchmarkDotNet/blob/f728f4a60a104c966b477a383a961e530df8d07a/src/BenchmarkDotNet.Core/Templates/BenchmarkProgram.txt#L28-L30), because [that code](https://github.com/DenisIstomin/BenchmarkDotNet/blob/f728f4a60a104c966b477a383a961e530df8d07a/src/BenchmarkDotNet.Core/Templates/BenchmarkProgram.txt#L39) does [JITting](https://github.com/PerfDotNet/BenchmarkDotNet/blob/master/src/BenchmarkDotNet.Core/Running/MethodInvoker.cs#L40-L42) itself. But I'm decided not to remove them.

**Comment by adamsitnik** [comment]
@DenisIstomin Thanks for the PR! Code looks good to me, I am merging ;)

**Comment by AndreyAkinshin** [comment]
@DenisIstomin,
> I think that there are some redundant operations
There are no any redundant operations.
1. It is very important to perform JITting of the `setup` and `target` methods as soon as possible (before any BenchmarkDotNet-specific code). E.g. `BenchmarkEnvironmentInfo.GetCurrent().ToFormattedString()` can significantly affect resulted asm code of the `target` method.
2. We can't skip the JITting phase in the `Invoke` method because we can't be sure that it was already done (it can be false for a custom toolchain).

**Comment by adamsitnik** [comment]
@AndreyAkinshin thanks for the explanation! Does it mean that you can close #184?

**Comment by AndreyAkinshin** [comment]
I think so. There is a suggestion in #184 to introduce an `Init` method, but I'm afraid of unexpected side-effects. The source code of `MethodInvoker` will be refactored anyway (I'm trying to do it right now).

**Comment by adamsitnik** [comment]
>The source code of MethodInvoker will be refactored anyway (I'm trying to do it right now). 

Great, I will implement #236 when you are done with this refactoring.

**Pull request merged**
